name: CI
on:
    push:
        branches: master
    pull_request:

jobs:
    test:
        name: Test
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                dc: [dmd-latest, ldc-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - name: Install D Compiler & Dub
              uses: mihails-strasuns/setup-dlang@v0.4.1
              with:
                  compiler: ${{ matrix.dc }}

            - name: Build & Run Tests
              run: dub run --config=test --build=unittest-cov
            
            - name: Code Coverage Report
              uses: codecov/codecov-action@v1.0.5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
